apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-inference-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton-inference-server
  template:
    metadata:
      labels:
        app: triton-inference-server
    spec:
      containers:
        - name: triton-inference-server
          image: cmpark0126/eks-triton-test:1st
          command: ["/bin/bash", "-c"]
          args:
            - |
              python tutorials/Quick_Deploy/PyTorch/export.py
              mv model.pt models/resnet50/1/model.pt
              tritonserver --model-repository models --allow-metrics true --allow-gpu-metrics true
          resources:
            limits:
              cpu: "3"
              memory: 10Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "3"
              memory: 10Gi
              nvidia.com/gpu: "1"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "node.kubernetes.io/instance-type"
                    operator: "In"
                    values: ["g4dn.xlarge"] # g4dn.xlarge for tesla t4, g5.xlarge for a10g
                  - key: "karpenter.sh/capacity-type"
                    operator: "In"
                    values: ["spot"]
