apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-job
spec:
  template:
    spec:
      containers:
        - name: gpu-job
          image: nvcr.io/nvidia/tritonserver:22.05-pyt-python-py3
          command: ["sh", "-c", "echo 'Hello, World!' && sleep 7200"]
          resources:
            limits:
              memory: 10Gi
              nvidia.com/gpu: "1"
            requests:
              memory: 10Gi
              nvidia.com/gpu: "1"
      restartPolicy: Never
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "node.kubernetes.io/instance-type"
                    operator: "In"
                    values: ["g4dn.xlarge"] # g4dn.xlarge for tesla t4, g5.xlarge for a10g
                  - key: "karpenter.sh/capacity-type"
                    operator: "In"
                    values: ["spot"]
  backoffLimit: 1
