apiVersion: apps/v1
kind: Deployment
metadata:
  name: trytune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trytune
  template:
    metadata:
      labels:
        app: trytune
    spec:
      serviceAccountName: s3-full-access-role
      containers:
        - name: trytune
          image: python:3.10.12-slim
          command: ["sleep", "7600"]
          resources:
            limits:
              cpu: "16"
              memory: 10Gi
            requests:
              cpu: "16"
              memory: 10Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "karpenter.sh/capacity-type"
                    operator: "In"
                    values: ["spot"]
