apiVersion: v1
kind: Service
metadata:
  name: server-1
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 8001
      targetPort: 8001
    - name: metric
      port: 8002
      targetPort: 8002
  selector:
    app: server-1
---
apiVersion: v1
kind: Service
metadata:
  name: server-2
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 8001
      targetPort: 8001
    - name: metric
      port: 8002
      targetPort: 8002
  selector:
    app: server-2
